cleaning up the email filters and adding slack filters
alleyinteractive/wp-updates-notifier pull request #10
Opened 2020-01-21 15:29 UTC by timatron

2020-01-21 15:39 UTC, mboynes requested changes
[All hooks should have docblocks](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters)

2020-02-19 13:51 UTC, renatonascalves approved these changes
🗡

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $message Email message.
```suggestion
			 * @param string  $message Email message.
```

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $subject Email subject line.
```suggestion
			 * @param string  $subject Email subject line.
```

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $username Username string.
```suggestion
			 * @param string  $username Username string.
```

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $user_icon Emoji string.
```suggestion
			 * @param string  $user_icon Emoji string.
```

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $settings['slack_webhook_url'] Webhook url.
```suggestion
			 * @param string  $settings['slack_webhook_url'] Webhook url.
```

2020-02-19 13:51 UTC, renatonascalves commented on class-sc-wp-updates-notifier.php
> +			 * @param String  $payload['channel'] Slack channel.
```suggestion
			 * @param string  $payload['channel'] Slack channel.
```

2020-02-25 19:38 UTC, merged